spring.application.name: redis-core
spring.profiles.active: local

spring:
  config:
    import:
      - db-core.yml
  mvc.throw-exception-if-no-handler-found: true
  web.resources.add-mappings: false

---
spring.config.activate.on-profile: local



---
spring.config.activate.on-profile: dev


---
spring.config.activate.on-profile: staging


---
spring.config.activate.on-profile: real

